/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "matrixOp.h"
#include<stdio.h>
#include<stdlib.h>
#include <time.h>
#include <unistd.h>


void printMatrix(int numberOfRows, int numberOfCols, float* data){

	int currentIndex = 0;
	for(int i = 0; i < numberOfRows; i++){

		for(int j = 0; j < numberOfCols; j++){

			printf("%f ",data[currentIndex++]);
		}

		printf("\n");
	}
}

void
matrix_operations_1( char* host, Input input, int opcode )
{
	CLIENT *clnt;
	Output  *result;
	
	clnt = clnt_create(host, MATRIX_OPERATIONS, MATRIX_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	if(opcode == 1){

		result = add_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}

		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.numOfRows,result->result.numOfCols,result->result.data);
		}

	}else if(opcode == 2){

		result = multiply_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}

		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.numOfRows,result->result.numOfCols,result->result.data);
		}

		

	}else if(opcode == 3){

		result = inverse_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}

		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.numOfRows,result->result.numOfCols,result->result.data);
		}

	}else{
		result = transpose_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}

		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.numOfRows,result->result.numOfCols,result->result.data);
		}
	}
	
	clnt_destroy( clnt );
}

void getUserInputMatrix(int numberOfRows, int numberOfCols, float* data){
	int currentIndex = 0;
	printf("Enter values for Matrix:\n");
    for (int i = 0; i < numberOfRows; i++) {
        for (int j = 0; j < numberOfCols; j++) {
            scanf("%f", &data[currentIndex++]);
        }
    }
}

void readMatrixFromFile(const char *filename, int *numberOfRows, int *numberOfCols, float* data){

	// Open the file for reading
    FILE *file = fopen(filename, "r");

    // Check if the file opened successfully
    if (file == NULL) {
        printf("Failed to open the file.\n");
        return;
    }

    // Read the dimensions of the matrix from the first line
    fscanf(file, "%d %d", numberOfRows, numberOfCols);
    
    int currentIndex = 0;

    for (int i = 0; i < *numberOfRows; i++) {
        for (int j = 0; j < *numberOfCols; j++) {
            fscanf(file, "%f", &data[currentIndex++]);
        }
    }

    // Close the file
    fclose(file);

}

main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	
	host = argv[1];
	
	int testMode = 0;
	
	if(argc > 2){
		testMode = 1;
	}
	
	while(1){
		Input input;
		int opcode;
	
		printf("Select an operation\n");
		printf("Press 1 for addition\nPress 2 for multiplication\nPress 3 for inverse\nPress 4 for transpose\n");
		

		srand(time(NULL));
		
		if(testMode == 0){

			scanf("%d",&opcode);

		}else{

			opcode = rand() % 4 + 1;
			printf("%d\n",opcode);
			sleep(3);
		}
		


		if(opcode == 1){

			input.numOfMatrices = 2;

			int numberOfRows, numberOfCols;

			if(testMode == 0){

				printf("Enter the number of rows: ");
    			scanf("%d", &numberOfRows);

    			printf("Enter the number of columns: ");
    			scanf("%d", &numberOfCols);

    

    			getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[0].data);

				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;
 
				getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[1].data);

				input.matrices[1].numOfRows = numberOfRows;
				input.matrices[1].numOfCols = numberOfCols;
			}
			else{

				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[0].data);
				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[0].data);
				sleep(3);

				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[1].data);
				input.matrices[1].numOfRows = numberOfRows;
				input.matrices[1].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[1].data);
				sleep(2);
			}
			


		}else if(opcode == 2){
		
			input.numOfMatrices = 2;

			int numberOfRows, numberOfCols;

			if(testMode == 0){

				printf("Enter the number of rows: ");
    			scanf("%d", &numberOfRows);

    			printf("Enter the number of columns: ");
    			scanf("%d", &numberOfCols);

    

    			getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[0].data);

				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;

				printf("Enter the number of rows: ");
    			scanf("%d", &numberOfRows);

    			printf("Enter the number of columns: ");
    			scanf("%d", &numberOfCols);

    

    			getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[1].data);

				input.matrices[1].numOfRows = numberOfRows;
				input.matrices[1].numOfCols = numberOfCols;

			}else{
				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[0].data);
				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[0].data);
				sleep(3);

				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[1].data);
				input.matrices[1].numOfRows = numberOfRows;
				input.matrices[1].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[1].data);
				sleep(2);
			}

			


		}else if(opcode == 3){

			input.numOfMatrices = 1;

			int numberOfRows, numberOfCols;


			if(testMode == 0){

				printf("Enter the order of the matrix: ");
    			scanf("%d", &numberOfRows);

				numberOfCols = numberOfRows;

    

    			getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[0].data);

				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;

			}else{

				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[0].data);
				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[0].data);
				sleep(2);
			}
			

		}else if(opcode == 4){

			input.numOfMatrices = 1;

			int numberOfRows, numberOfCols;

			if(testMode == 0){

				printf("Enter the number of rows: ");
    			scanf("%d", &numberOfRows);

    			printf("Enter the number of columns: ");
    			scanf("%d", &numberOfCols);

    

    			getUserInputMatrix(numberOfRows,numberOfCols,input.matrices[0].data);

				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;

			}else{

				readMatrixFromFile("matrix.txt",&numberOfRows,&numberOfCols,input.matrices[0].data);
				input.matrices[0].numOfRows = numberOfRows;
				input.matrices[0].numOfCols = numberOfCols;
				printf("Enter the number of rows: %d\n",numberOfRows);
				printf("Enter the number of columns: %d\n",numberOfCols);
				printMatrix(numberOfRows,numberOfCols,input.matrices[0].data);
				sleep(2);
			}

			

		}else{
			printf("Invalid input\n");
			return -1;
		}
		matrix_operations_1( host,input,opcode );

	}
	
}
